#!/bin/bash
# ============================================================================
# SKY130 BSIM4 Simulation Runner
# ============================================================================
# Runs multi-corner PVT analysis for the redesigned STI cell
#
# Usage: run_bsim4_sim.sh [testbench] [corner]
#   testbench: Name of testbench file (default: sti_multivth_sky130)
#   corner: tt, ss, ff, sf, fs (default: all)
# ============================================================================

set -e

TESTBENCH=${1:-sti_multivth_sky130}
CORNER=${2:-all}
SPICE_DIR="/tritone/spice"
RESULTS_DIR="$SPICE_DIR/results"
PDK_DIR="/tritone/pdk/sky130_fd_pr"

mkdir -p "$RESULTS_DIR"

echo "============================================"
echo "SKY130 BSIM4 Multi-Vth STI Characterization"
echo "============================================"
echo "Testbench: $TESTBENCH"
echo "Corner: $CORNER"
echo "PDK: $PDK_DIR"
echo "Results: $RESULTS_DIR"
echo ""

# Function to run a single corner
run_corner() {
    local corner=$1
    echo "=== Running $corner corner ==="

    # Create corner-specific testbench
    cat > "$RESULTS_DIR/${TESTBENCH}_${corner}.spice" << EOF
* SKY130 Multi-Vth STI - $corner Corner
* Auto-generated by run_bsim4_sim.sh

* Include SKY130 BSIM4 models for $corner corner
.include "$PDK_DIR/models/corners/${corner}.spice"

* Include the redesigned STI cell
.include "$SPICE_DIR/cells/sti_multivth_sky130.spice"

* Power supplies
.param VDD_NOM = 1.8
VDD vdd 0 DC {VDD_NOM}
VSS vss 0 DC 0

* Input stimulus
VIN in 0 DC 0

* Device under test
XDUT in out vdd vss STI_MULTIVTH_SKY130

* Control script
.control
set filetype = ascii

* DC sweep
echo "Running DC sweep for $corner corner..."
dc VIN 0 1.8 0.01

* Save results
wrdata $RESULTS_DIR/dc_transfer_${corner}.dat v(out)

* Measure key metrics
meas dc vout_low FIND v(out) AT=0
meas dc vout_mid FIND v(out) AT=0.9
meas dc vout_high FIND v(out) AT=1.8
meas dc vil_th WHEN v(out)=1.35 CROSS=1
meas dc vih_th WHEN v(out)=0.45 CROSS=1

* Print results
echo ""
echo "=== $corner Corner Results ==="
echo "Vout @ Vin=0.0V: \$&vout_low V (expect ~1.8V)"
echo "Vout @ Vin=0.9V: \$&vout_mid V (expect ~0.9V)"
echo "Vout @ Vin=1.8V: \$&vout_high V (expect ~0.0V)"
echo "VIL threshold: \$&vil_th V"
echo "VIH threshold: \$&vih_th V"
echo ""

* Calculate noise margins
let nmh = 1.8 - vih_th
let nml = vil_th
let nmm = min(vout_mid - 0.45, 1.35 - vout_mid)
echo "Noise Margins:"
echo "  NMH: \$&nmh V"
echo "  NML: \$&nml V"
echo "  NMM: \$&nmm V"

quit
.endc

.end
EOF

    # Run ngspice
    ngspice -b "$RESULTS_DIR/${TESTBENCH}_${corner}.spice" > "$RESULTS_DIR/${TESTBENCH}_${corner}.log" 2>&1

    echo "Results saved to $RESULTS_DIR/${TESTBENCH}_${corner}.log"
}

# Run specified corners
if [ "$CORNER" = "all" ]; then
    for c in tt ss ff sf fs; do
        run_corner $c
    done
else
    run_corner $CORNER
fi

echo ""
echo "============================================"
echo "Simulation Complete"
echo "============================================"
echo ""
echo "Summary of results:"
for log in $RESULTS_DIR/${TESTBENCH}_*.log; do
    if [ -f "$log" ]; then
        corner=$(basename "$log" .log | sed "s/${TESTBENCH}_//")
        echo ""
        echo "--- $corner corner ---"
        grep -A5 "Results ===" "$log" 2>/dev/null || echo "  (parsing failed)"
    fi
done
